# Generated by Django 5.1.3 on 2024-11-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('programming', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=100)),
                ('computer_access', models.CharField(max_length=3)),
                ('internet_access', models.CharField(max_length=3)),
            ],
        ),
    ]
